mrt_train_graph = {
    # RED LINE
    'Toa Payoh': {'Novena': 1, 'Braddel': 1},
    'Novena': {'Newton': 1, 'Toa Payoh': 1},
    'Newton': {'Novena': 1, 'Orchard': 1},
    'Orchard': {'Newton': 1, 'Somerset': 1},
    'Somerset': {'Dhoby Ghaut': 2, 'Orchard': 1},
    ### INTERCHANGE
    'Dhoby Ghaut': {'Clarke Quay': 2, 'Little India': 2, 'Bras Basah': 2, 'Somerset': 2, 'City Hall': 2},
    # PURPLE LINE
    'Little India': {'Farrer Park': 1, 'Dhoby Ghaut': 2},
    'Farrer Park': {'Boon Keng': 1, 'Little India': 1},
    'Boon Keng': {'Farrer Park': 1, 'Potong Pasir': 1},
    'Potong Pasir': {'Boon Keng': 1, 'Woodleigh': 1},
    'Woodleigh': {'Potong Pasir': 1, 'Serangoon': 2},
    ### INTERCHANGE
    'Serangoon': {'Woodleigh': 2, 'Kovan': 2, 'Bartley': 2, 'Lorong Chuan': 2},
    # PURPLE LINE
    'Kovan': {'Hougang': 1, 'Serangoon': 2},
    'Hougang': {'Kovan': 1, 'Buangkok': 1},
    'Buangkok': {'Hougang': 1, 'Sengkang': 2},
    'Sengkang': {'Buangkok': 2, 'Punggol': 2, 'Sengkang LRT': 2},
    'Punggol': {'Sengkang': 2, 'Punggol LRT': 2},
    # LRT
    'Sengkang LRT': {'Sengkang': 2},
    'Punggol LRT': {'Punggol': 2},
    # LAST PURPLE LINE
    'Clarke Quay': {'Dhoby Ghaut': 2, 'Chinatown': 1},
    'Chinatown': {'Clarke Quay': 1, 'Outram Park': 2},
    'Outram Park': {'Chinatown': 2, 'HarbourFront': 2, 'Tiong Bahru': 2, 'Tanjong Pagar': 2},
    'HarbourFront': {'Outram Park': 2},
    # GREEN LINE
    'Tiong Bahru': {'Outram Park': 2, 'Redhill': 1},
    'Redhill': {'Tiong Bahru': 1, 'Queenstown': 1},
    'Queenstown': {'Redhill': 1, 'Commonwealth': 1},
    'Commonwealth': {'Queenstown': 1, 'Buona Vista': 1},
    'Buona Vista': {'Commonwealth': 1, 'Dover': 1},
    'Dover': {'Buona Vista': 1, 'Clementi': 1},
    'Clementi': {'Dover': 1, 'Jurong East': 2},
    ### INTERCHANGE
    'Jurong East': {'Bukit Batok': 2, 'Clementi': 2, 'Chinese Garden': 2},
    # GREEN LINE
    'Chinese Garden': {'Jurong East': 2, 'Lakeside': 1},
    'Lakeside': {'Boon Lay': 1, 'Chinese Garden': 1},
    'Boon Lay': {'Lakeside': 1, 'Pioneer': 1},
    'Pioneer': {'Boon Lay': 1, 'Joo Koon': 1},
    'Joo Koon': {'Pioneer': 1},
    # LAST GREEN LINE
    'Tanjong Pagar': {'Outram Park': 2, 'Raffles Place': 2},
    'Raffles Place': {'Tanjong Pagar': 2, 'Marina Bay': 2, 'City Hall': 2},
    'City Hall': {'Raffles Place': 2, 'Bugis': 2, 'Dhoby Ghaut': 2},
    'Bugis': {'City Hall': 2, 'Lavender': 1},
    'Lavender': {'Bugis': 1, 'Kallang': 1},
    'Kallang': {'Lavender': 1, 'Aljunied': 1},
    'Aljunied': {'Kallang': 1, 'Paya Lebar': 2},
    'Paya Lebar': {'Eunos': 2, 'Aljunied': 2, 'MacPherson': 2, 'Dakota': 2},
    'Eunos': {'Paya Lebar': 2, 'Kembangan': 1},
    'Kembangan': {'Eunos': 1, 'Bedok': 1},
    'Bedok': {'Kembangan': 1, 'Tanah Merah': 2},
    'Tanah Merah': {'Simei': 2, 'Expo': 2, 'Bedok': 2},
    'Simei': {'Tanah Merah': 2, 'Tampines': 1},
    'Tampines': {'Simei': 1, 'Pasir Ris': 1},
    'Pasir Ris': {'Tampines': 1},
    'Expo': {'Tanah Merah': 2, 'Changi Airport': 1},
    'Changi Airport': {'Expo': 1},
    # LAST RED LINE
    'Marina Bay': {'Raffles Place': 2},
    'Braddel': {'Toa Payoh': 1, 'Bishan': 2},
    'Bishan': {'Braddel': 2, 'Marymount': 2, 'Lorong Chuan': 2, 'Ang Mo Kio': 2},
    'Ang Mo Kio': {'Bishan': 2, 'Yio Chu Kang': 1},
    'Yio Chu Kang': {'Ang Mo Kio': 1, 'Khatib': 1},
    'Khatib': {'Yio Chu Kang': 1, 'Yishun': 1},
    'Yishun': {'Khatib': 1, 'Sembawang': 1},
    'Sembawang': {'Yishun': 1, 'Admiralty': 1},
    'Admiralty': {'Sembawang': 1, 'Woodlands': 1},
    'Woodlands': {'Admiralty': 1, 'Marsiling': 1},
    'Marsiling': {'Woodlands': 1, 'Kranji': 1},
    'Kranji': {'Marsiling': 1, 'Yew Tee': 1},
    'Yew Tee': {'Kranji': 1, 'Choa Chu Kang': 2},
    'Choa Chu Kang': {'Yew Tee': 2, 'Bukit Gombak': 2, 'Bukit Panjang LRT': 2},
    'Bukit Panjang LRT': {'Choa Chu Kang': 2},
    'Bukit Gombak': {'Choa Chu Kang': 2, 'Bukit Batok': 2},
    'Bukit Batok': {'Bukit Gombak': 1, 'Jurong East': 2},
    # LAST YELLOW LINE
    'Bras Basah': {'Dhoby Ghaut': 2, 'Esplanade': 1},
    'Esplanade': {'Bras Basah': 1, 'Promenade': 1},
    'Promenade': {'Esplanade': 1, 'Nicoll Highway': 1},
    'Nicoll Highway': {'Promenade': 1, 'Stadium': 1},
    'Stadium': {'Nicoll Highway': 1, 'Mountbatten': 1},
    'Mountbatten': {'Stadium': 1, 'Dakota': 1},
    'Dakota': {'Mountbatten': 1, 'Paya Lebar': 2},
    'MacPherson': {'Paya Lebar': 2, 'Tai Seng': 1},
    'Tai Seng': {'MacPherson': 1, 'Bartley': 1},
    'Bartley': {'Tai Seng': 1, 'Serangoon': 2},
    'Lorong Chuan': {'Serangoon': 2, 'Bishan': 2},
    'Marymount': {'Bishan': 2}
}